name: ansible-lint
on:
  workflow_dispatch:
  push:
    branches: ["main", "stable", "release/v*"]
  #pull_request:
    #branches: ["main", "stable", "release/v*"]
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ansible/
        
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main # or version tag instead of 'main'
        with:
          targets: ./ansible/*
