name: 'Ansible'

on:
  #push:
  workflow_dispatch:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest
    #environment: production

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: playbook-docker.yaml
        # Optional, directory where playbooks live
        directory: ./ansible
        # Optional, ansible configuration file content (ansible.cfg)
        configuration: |
          [defaults]
          callbacks_enabled = ansible.posix.profile_tasks, ansible.posix.timer
          stdout_callback = yaml
          nocows = false
        # Optional, SSH private key
        key: ${{secrets.SSH_PRIVATE_KEY}}
        # Optional, literal inventory file contents
        inventory: host.ini
